import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { useState } from 'react'


import { useDetectAdBlock } from 'adblock-detect-react'

export default function Home() {


  const adBlockDetected = useDetectAdBlock();


  const defaultAdd = {
    detect: 'Detecting....',
    detecting: 'Please Wait',

  }
  const [state, setState] = useState(defaultAdd)
  setTimeout(() => {
    setState({
      detect: 'AdBlock Detected!',
      detecting: 'Our Website is made possible by displaying online advertisements to our visitors. Please consider supporting us by disabling your ad blocker on our website.',

    })
  }, 5000)

  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {
        adBlockDetected && <div>
          <div className={styles.modalfader}></div>
          <div className={styles.modalwindow}>
          <div className={styles.wrapper}>
            
            <img className={styles.img} src='/adblock.png' />
            <p className={styles.detect}>{state.detect}</p>
            <p className={styles.adp}>{state.detecting}</p>
          </div>
           
          </div>

        </div>

      }



      <main className={styles.main}>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>
        <h1>Welcome To the APp</h1>


      </main>


    </div>
  )
}
